/**
 * This file was automatically generated by fer: file-express-router.
 * Generated on: Thursday, April 3, 2025 at 11:18:18 PM GMT+5:30
 * Do not modify it manually.
 */
import { Router } from 'express';
import a from './error.error';
import b from './hello.get';
import c from './index.get';
import d from './users/auth.middleware';
import e from './users/authz.middleware';
import f from './users/create.post';
import g from './users/index.get';
import h from './users/update.delete';
import i from './[path]/home.get';
import j from './[path]/name/hello.get';

const k = Router({ mergeParams: true });

// (root)
const l = Router({ mergeParams: true });

l.get('/hello', b);
l.get('/', c);

// users
const m = Router({ mergeParams: true });
m.use(d);
m.use(e);
m.post('/create', f);
m.get('/', g);
m.delete('/update', h);

l.use('/users', m);

// [path]
const n = Router({ mergeParams: true });

n.get('/home', i);

// [path]/name
const o = Router({ mergeParams: true });

o.get('/hello', j);

n.use('/name', o);

l.use('/:path', n);

l.use(a);
k.use('/', l);

export default k;
