/**
 * This file was automatically generated by fer: file-express-router.
 * Generated on: Tuesday, April 1, 2025 at 7:17:17 PM GMT+5:30
 * Do not modify it manually.
 */
import { Router } from 'express';
import a from './error.error';
import b from './hello.get';
import c from './index.get';
import d from './users/auth.middleware';
import e from './users/authz.middleware';
import f from './users/create.post';
import g from './users/index.get';
import h from './users/update.delete';
import i from './[path]/home.get';
import j from './[path]/name/hello.get';

const k = Router({ mergeParams: true });

// (root)
const l = Router({ mergeParams: true });

k.use('/', l);
l.get('/hello', b);
l.get('/', c);

// users
const m = Router({ mergeParams: true });
l.use(d);
l.use(e);
l.use('/users', m);
m.post('/create', f);
m.get('/', g);
m.delete('/update', h);

// [path]
const n = Router({ mergeParams: true });

l.use('/:path', n);
n.get('/home', i);

// [path]/name
const o = Router({ mergeParams: true });

n.use('/name', o);
o.get('/hello', j);

k.use(a);

export default k;
